### ISSUE TITLE
About population counts

### ISSUE THREAD

**Issue by syounkin** [ITHIM/ITHIM#16]
It seems like there is only one population count file (F.csv). It is used to calculate population mean active travel time for both baseline and scenario. But in our case, the scenario is in future year, and the population counts in future year is different from the baseline counts. So, I’m wondering if we could add one more file (e.g. F.scenario.csv) to store the future year population counts? And revise the calculation method for future year mean active travel time accordingly.  And last time, you mentioned we could update F file by using:

`createITHIM(activeTransportFile = "filename", GBDFile = "filename", FFile = "filename")`

But actually, _FFile_ is not included in this `createITHIM()` function.

Issue from Yizheng Wu (@yzhwu)

**Comment by syounkin** [comment]
Thanks @yzhwu.

Re: _FFile_: Please make sure you have installed the `devel` branch.  I know the example is working and the example uses the above syntax.  Please let me know if the problem persists.

Re: _F.scenario.csv_ Yes, we could do that.  Alternatively, one can use `update` to update _F_ within an R session.  What burden values did you use for the future scenario?  Baseline or Scenario?

**Comment by syounkin** [comment]
@yzhwu We can return to creating different population distributions for each scenario.  For now we will leave it as part of an `update` step.

**Comment by yzhwu** [comment]
I see. The function "createITHIM" works fine now. And the latest version is 0.7.2, right?
