### ISSUE TITLE
Non-travel METs

### ISSUE THREAD

**Issue by yzhwu** [ITHIM/ITHIM#17]
Is it possible to make it as a .csv file just like F.csv and GBD.csv?
It is not easy to update it by using the ‘update’ function especially for those matrices. Could you please put an example in tutorial about how to use the ‘update’ function to update those parameters, especially those matrices?

**Comment by syounkin** [comment]
@yzhwu The updated `devel` branch now uses an EXCEL flag.  If set to TRUE then the non-travel METs quintiles are read in from a file and added directly to travel METs, as in the EXCEL workbook.  

`ITHIM.object <- update(ITHIM.object, EXCEL = TRUE)`

Note that the file is in terms of quintiles and so the ITHIM objects will also need to be configured to quintiles.  Why don't you create a local version of the `devel` branch and update the code to accept a filename for non-travel METs?  If that goes well, then submit a pull request to the _ITHIM_ repository and I'll merge in your changes.

See the function [getQuintiles](https://github.com/ITHIM/ITHIM/blob/9e13a40ea2c86e18b1813c1e055125edc5a7ed05/R/functions-PA.R#L184-L220).

Have you had any luck with the `update` method?  Have you been able to follow the tutorial on the wiki page [here](https://github.com/ITHIM/ITHIM/wiki/Tutorial)?

Thanks.

**Comment by syounkin** [comment]
@yzhwu Any progress on this issue?  Thanks.

**Comment by syounkin** [comment]
@yzhwu Just following up on your progress.  Thanks.

**Comment by syounkin** [comment]
It is unlikely that I will make significant changes to this version of the physical activity component of ITHIM.  Development of _ITHIM 3.0_ is underway and so this version will likely soon be deprecated.  Please send suggestions on how to treat non-travel physical activity in the model.  The plan now is to treat it as an independent log-normal random variable with mean and standard deviation estimated from data or supplied by the user.  Incorporating correlation between travel and non-travel physical activity is a natural extension of this model.  Please send comments.  Thanks.

**Comment by yzhwu** [comment]
That's great. The "update" method now works great, and the tutorial is really helpful.
