### ISSUE TITLE
Results table

### ISSUE THREAD

**Issue by vargovargo** [ITHIM/ITHIM#19]
Can we have a function that produces a table of results in tidy format by age-sex-cause-burden type that is then used to create results plots?  Would be usefule toninclude some columns for baseline and scenario parameters used in the CRA. Lastly we could have an option to produce the value of the Delta (ie daly reduced) or percent reduction.

**Comment by syounkin** [comment]
The new function _superTabulate_ is pretty close.  See documentation `help(superTabulate)`.  @vargovargo Perhaps you can add to the documentation [here](https://github.com/ITHIM/ITHIM/blob/9e13a40ea2c86e18b1813c1e055125edc5a7ed05/R/functions-ITHIM.R#L234-L265)?  Thanks.

**Comment by vargovargo** [comment]
if I supply a single ITHIM object for the second argument (instead of an ITHIM list)  I get this error


> Error in for (ITHIM.scenario in ITHIM.scenario.list) { : 
>   invalid for() loop sequence

**Comment by vargovargo** [comment]
testing superTabulate


```
devtools::install_github("ITHIM/ITHIM", ref="devel", force=TRUE)
library("ITHIM")

PAexamplePath <- system.file("activeTravelOHAS.csv", package = "ITHIM")
BURexamplePath <- system.file("burden.portland.csv", package = "ITHIM")
POPexamplePath <- system.file("F.portland.11_21_2017.csv", package = "ITHIM")

base <-  createITHIM(activeTransportFile = PAexamplePath, GBDFile = BURexamplePath, FFile = POPexamplePath)

double <- update(x = base, parList = list(muwt = base@parameters@muwt*2, muct = base@parameters@muct*2))

triple <- update(x = base, parList = list(muwt = base@parameters@muwt*3, muct = base@parameters@muct*3))

superTabulate(ITHIM.baseline = base, ITHIM.scenario.list = list(double, triple))
```
receive this error

> Error in data.frame(foobar, ageClass = paste0("ageClass", 1:8), burdenType = gsub(".delta",  : 
>   arguments imply differing number of rows: 96, 8, 1, 0

**Comment by syounkin** [comment]
Below is the corrected code.

The list of scenario objects must be a named list.  I'll create an issue to fix the bug.

```
devtools::install_github("ITHIM/ITHIM", ref="devel", force=TRUE)
library("ITHIM")

PAexamplePath <- system.file("activeTravelOHAS.csv", package = "ITHIM")
BURexamplePath <- system.file("burden.portland.csv", package = "ITHIM")
POPexamplePath <- system.file("F.portland.11_21_2017.csv", package = "ITHIM")

base <-  createITHIM(activeTransportFile = PAexamplePath, GBDFile = BURexamplePath, FFile = POPexamplePath)

double <- update(x = base, parList = list(muwt = base@parameters@muwt*2, muct = base@parameters@muct*2))

triple <- update(x = base, parList = list(muwt = base@parameters@muwt*3, muct = base@parameters@muct*3))

superTabulate(ITHIM.baseline = base, ITHIM.scenario.list = list(double = double, triple = triple))
```

**Comment by syounkin** [comment]
@vargovargo Any progress on this issue?

**Comment by syounkin** [comment]
`superTabulate` is currently functional and gives output similar to the _Health Summary_ worksheet in the Excel workbook.  Please create a new issue if further tabulation is required.  Thanks.
