### ISSUE TITLE
ITHIM R Package Error

### ISSUE THREAD

**Issue by PaaBobo** [ITHIM/ITHIM#23]
"
> **library("devtools")
> install_github("ITHIM/ITHIM", ref="devel")**
Downloading GitHub repo ITHIM/ITHIM@devel
from URL https://api.github.com/repos/ITHIM/ITHIM/zipball/devel
Installing ITHIM
Installing 1 package: reshape2
Installing package into ‘C:/.../R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/reshape2_1.4.3.zip'
Content type 'application/zip' length 611425 bytes (597 KB)
downloaded 597 KB

package ‘reshape2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\.....\RtmpwZZkhk\downloaded_packages
Installing 1 package: tidyverse
Installing package into ‘C:/...../R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/tidyverse_1.2.1.zip'
Content type 'application/zip' length 82090 bytes (80 KB)
downloaded 80 KB

package ‘tidyverse’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\....\RtmpwZZkhk\downloaded_packages
"C:/PROGRA~1/R/R-33~1.3/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/..../RtmpwZZkhk/devtools9dc397d3643/ITHIM-ITHIM-f37748c"  \
  --library="C:/.....R/win-library/3.3" --install-tests 

Error in setwd(dir = new) : cannot change working directory
**> library("ITHIM")**
Error in library("ITHIM") : there is no package called ‘ITHIM’
> 
"

**Comment by syounkin** [comment]
@PaaBobo I notice that this script was run on a Windows machine.  This is not the first time I have seen strange bugs on Windows machines.  Please see this [bug report](https://gist.github.com/sebkopf/3cf82afb2e535e92f2cfcf3e66d48475) for the package _devtools_.  I hope the advice there makes this bug go away.

I recommend running `install.packages(c("tidyverse","reshape2", "knitr","testthat"), depen = T)` before `install_github()`.

It seems `install_github()` failed here with an error message about `setwd()`.  Perhaps you don't have permission to access a temporary directory that _devtools_ uses for installation.  Hopefully the above update to _devtools_ will correct this.

**Comment by usr110** [comment]
> It seems install_github() failed here with an error message about setwd(). Perhaps you don't have permission to access a temporary directory that devtools uses for installation

In my experience if you run RStudio (or R) in administrative mode, this does not appear.

**Comment by PaaBobo** [comment]
Thank you. I will run R Studio as an administrator and run the script again. 
Best Regards.

**Comment by PaaBobo** [comment]
Thank you. I am using windows.
I will re-run R Studio with the suggested changes.

**Comment by syounkin** [comment]
@PaaBobo I believe I have found and corrected the bug.  The above solution may be unnecessary Please be sure to use the `devel` branch and confirm that it works.  Thanks.

**Comment by syounkin** [comment]
The bug occurred because the file _nonTravelMETs.csv_ in the _inst_ directory had an invisible byte order mark (BOM) at the beginning of the file.  This caused the variable name to be something like "?sex" instead of "sex" and this caused an error in the following _split_ function.  On Mac and linux the BOM was ignored.

I have stripped the BOM with:

`find . -type f -exec sed '1s/^\xEF\xBB\xBF//' -i {} \;`

I also now explicitly name the variables, just to be sure.

Please let me know if you still have problems.
